// kt4: autogenerated from k_gemv_q4_0_batch4_kt2 (4 tiles).
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <stdio.h>
typedef struct { half d; uint8_t qs[16]; } BlockQ4_0;
__device__ __forceinline__ float kt4_wrs(float v) {
#pragma unroll
  for (int o=16;o>0;o/=2) v+=__shfl_down_sync(0xffffffff,v,o);
  return v; }
__global__ void k_gemv_q4_0_batch4_kt4(const BlockQ4_0 *__restrict__ W,
                                    const float    *__restrict__ X,
                                    float          *__restrict__ Y,
                                    int M, int K) {
    extern __shared__ float sx[];   // [4][KT]
    const int lane = threadIdx.x;
    const int warp = threadIdx.y;
    const int tid = warp * 32 + lane;
    const int row0 = (blockIdx.x * blockDim.y + warp) * 4;
    const int row1 = row0 + 1, row2 = row0 + 2, row3 = row0 + 3;
    const int nb   = K / 32;
    const int KT = K >> 2;
    const int nb4 = nb >> 2;
    const uint32_t *rw0 = (const uint32_t *)((const char *)W + (long)row0 * nb * 18);
    const uint32_t *rw1 = (const uint32_t *)((const char *)W + (long)row1 * nb * 18);
    const uint32_t *rw2 = (const uint32_t *)((const char *)W + (long)row2 * nb * 18);
    const uint32_t *rw3 = (const uint32_t *)((const char *)W + (long)row3 * nb * 18);
    const float4 *sx4_0 = (const float4 *)(sx + 0 * KT);
    const float4 *sx4_1 = (const float4 *)(sx + 1 * KT);
    const float4 *sx4_2 = (const float4 *)(sx + 2 * KT);
    const float4 *sx4_3 = (const float4 *)(sx + 3 * KT);
    float s00 = 0.f, s01 = 0.f, s02 = 0.f, s03 = 0.f;
    float s10 = 0.f, s11 = 0.f, s12 = 0.f, s13 = 0.f;
    float s20 = 0.f, s21 = 0.f, s22 = 0.f, s23 = 0.f;
    float s30 = 0.f, s31 = 0.f, s32 = 0.f, s33 = 0.f;
    for (int t = 0; t < 4; t++) {
        const int total = 4 * KT;
        for (int i = tid; i < total; i += 512) {
            const int c = i / KT;
            const int kk = i % KT;
            sx[i] = X[(long)c * K + (long)t * KT + kk];
        }
        __syncthreads();
        if (row0 < M) {
        for (int b = lane; b < nb4; b += 32) {
            const int b_g = t * nb4 + b;
            const int wsc = (18 * b_g) >> 2;
            const int sh  = (18 * b_g + 2) & 2;
            const unsigned short d16a = (unsigned short)
                (((18 * b_g) & 2) ? (rw0[wsc] >> 16) : (rw0[wsc] & 0xFFFFu));
            const unsigned short d16b = (unsigned short)
                (((18 * b_g) & 2) ? (rw1[wsc] >> 16) : (rw1[wsc] & 0xFFFFu));
            const unsigned short d16c = (unsigned short)
                (((18 * b_g) & 2) ? (rw2[wsc] >> 16) : (rw2[wsc] & 0xFFFFu));
            const unsigned short d16d = (unsigned short)
                (((18 * b_g) & 2) ? (rw3[wsc] >> 16) : (rw3[wsc] & 0xFFFFu));
            const float da = __half2float(__ushort_as_half(d16a));
            const float db = __half2float(__ushort_as_half(d16b));
            const float dc = __half2float(__ushort_as_half(d16c));
            const float dd = __half2float(__ushort_as_half(d16d));
            const int a0 = (18 * b_g + 2) >> 2;
            const int x_off = b * 8;
#pragma unroll
            for (int k = 0; k < 4; k++) {
                const uint32_t la0 = __ldg(rw0 + a0 + k);
                const uint32_t la1 = __ldg(rw1 + a0 + k);
                const uint32_t la2 = __ldg(rw2 + a0 + k);
                const uint32_t la3 = __ldg(rw3 + a0 + k);
                const uint32_t va0 = sh ? __byte_perm(la0, __ldg(rw0 + a0 + k + 1), 0x5432) : la0;
                const uint32_t va1 = sh ? __byte_perm(la1, __ldg(rw1 + a0 + k + 1), 0x5432) : la1;
                const uint32_t va2 = sh ? __byte_perm(la2, __ldg(rw2 + a0 + k + 1), 0x5432) : la2;
                const uint32_t va3 = sh ? __byte_perm(la3, __ldg(rw3 + a0 + k + 1), 0x5432) : la3;
                const float a0_0 = (float)((int)( va0         & 0xFu) - 8) * da;
                const float a0_1 = (float)((int)((va0 >>  4)  & 0xFu) - 8) * da;
                const float a0_2 = (float)((int)((va0 >>  8)  & 0xFu) - 8) * da;
                const float a0_3 = (float)((int)((va0 >> 12)  & 0xFu) - 8) * da;
                const float a0_4 = (float)((int)((va0 >> 16)  & 0xFu) - 8) * da;
                const float a0_5 = (float)((int)((va0 >> 20)  & 0xFu) - 8) * da;
                const float a0_6 = (float)((int)((va0 >> 24)  & 0xFu) - 8) * da;
                const float a0_7 = (float)((int)( va0 >> 28)        - 8) * da;
                const float a1_0 = (float)((int)( va1         & 0xFu) - 8) * db;
                const float a1_1 = (float)((int)((va1 >>  4)  & 0xFu) - 8) * db;
                const float a1_2 = (float)((int)((va1 >>  8)  & 0xFu) - 8) * db;
                const float a1_3 = (float)((int)((va1 >> 12)  & 0xFu) - 8) * db;
                const float a1_4 = (float)((int)((va1 >> 16)  & 0xFu) - 8) * db;
                const float a1_5 = (float)((int)((va1 >> 20)  & 0xFu) - 8) * db;
                const float a1_6 = (float)((int)((va1 >> 24)  & 0xFu) - 8) * db;
                const float a1_7 = (float)((int)( va1 >> 28)        - 8) * db;
                const float a2_0 = (float)((int)( va2         & 0xFu) - 8) * dc;
                const float a2_1 = (float)((int)((va2 >>  4)  & 0xFu) - 8) * dc;
                const float a2_2 = (float)((int)((va2 >>  8)  & 0xFu) - 8) * dc;
                const float a2_3 = (float)((int)((va2 >> 12)  & 0xFu) - 8) * dc;
                const float a2_4 = (float)((int)((va2 >> 16)  & 0xFu) - 8) * dc;
                const float a2_5 = (float)((int)((va2 >> 20)  & 0xFu) - 8) * dc;
                const float a2_6 = (float)((int)((va2 >> 24)  & 0xFu) - 8) * dc;
                const float a2_7 = (float)((int)( va2 >> 28)        - 8) * dc;
                const float a3_0 = (float)((int)( va3         & 0xFu) - 8) * dd;
                const float a3_1 = (float)((int)((va3 >>  4)  & 0xFu) - 8) * dd;
                const float a3_2 = (float)((int)((va3 >>  8)  & 0xFu) - 8) * dd;
                const float a3_3 = (float)((int)((va3 >> 12)  & 0xFu) - 8) * dd;
                const float a3_4 = (float)((int)((va3 >> 16)  & 0xFu) - 8) * dd;
                const float a3_5 = (float)((int)((va3 >> 20)  & 0xFu) - 8) * dd;
                const float a3_6 = (float)((int)((va3 >> 24)  & 0xFu) - 8) * dd;
                const float a3_7 = (float)((int)( va3 >> 28)        - 8) * dd;
                const float4 xa0 = sx4_0[x_off + k],     xb0 = sx4_0[x_off + k + 4];
                const float4 xa1 = sx4_1[x_off + k],     xb1 = sx4_1[x_off + k + 4];
                const float4 xa2 = sx4_2[x_off + k],     xb2 = sx4_2[x_off + k + 4];
                const float4 xa3 = sx4_3[x_off + k],     xb3 = sx4_3[x_off + k + 4];
                s00 += a0_0 * xa0.x;  s00 += a0_1 * xb0.x;
                s00 += a0_2 * xa0.y;  s00 += a0_3 * xb0.y;
                s00 += a0_4 * xa0.z;  s00 += a0_5 * xb0.z;
                s00 += a0_6 * xa0.w;  s00 += a0_7 * xb0.w;
                s01 += a0_0 * xa1.x;  s01 += a0_1 * xb1.x;
                s01 += a0_2 * xa1.y;  s01 += a0_3 * xb1.y;
                s01 += a0_4 * xa1.z;  s01 += a0_5 * xb1.z;
                s01 += a0_6 * xa1.w;  s01 += a0_7 * xb1.w;
                s02 += a0_0 * xa2.x;  s02 += a0_1 * xb2.x;
                s02 += a0_2 * xa2.y;  s02 += a0_3 * xb2.y;
                s02 += a0_4 * xa2.z;  s02 += a0_5 * xb2.z;
                s02 += a0_6 * xa2.w;  s02 += a0_7 * xb2.w;
                s03 += a0_0 * xa3.x;  s03 += a0_1 * xb3.x;
                s03 += a0_2 * xa3.y;  s03 += a0_3 * xb3.y;
                s03 += a0_4 * xa3.z;  s03 += a0_5 * xb3.z;
                s03 += a0_6 * xa3.w;  s03 += a0_7 * xb3.w;
                s10 += a1_0 * xa0.x;  s10 += a1_1 * xb0.x;
                s10 += a1_2 * xa0.y;  s10 += a1_3 * xb0.y;
                s10 += a1_4 * xa0.z;  s10 += a1_5 * xb0.z;
                s10 += a1_6 * xa0.w;  s10 += a1_7 * xb0.w;
                s11 += a1_0 * xa1.x;  s11 += a1_1 * xb1.x;
                s11 += a1_2 * xa1.y;  s11 += a1_3 * xb1.y;
                s11 += a1_4 * xa1.z;  s11 += a1_5 * xb1.z;
                s11 += a1_6 * xa1.w;  s11 += a1_7 * xb1.w;
                s12 += a1_0 * xa2.x;  s12 += a1_1 * xb2.x;
                s12 += a1_2 * xa2.y;  s12 += a1_3 * xb2.y;
                s12 += a1_4 * xa2.z;  s12 += a1_5 * xb2.z;
                s12 += a1_6 * xa2.w;  s12 += a1_7 * xb2.w;
                s13 += a1_0 * xa3.x;  s13 += a1_1 * xb3.x;
                s13 += a1_2 * xa3.y;  s13 += a1_3 * xb3.y;
                s13 += a1_4 * xa3.z;  s13 += a1_5 * xb3.z;
                s13 += a1_6 * xa3.w;  s13 += a1_7 * xb3.w;
                s20 += a2_0 * xa0.x;  s20 += a2_1 * xb0.x;
                s20 += a2_2 * xa0.y;  s20 += a2_3 * xb0.y;
                s20 += a2_4 * xa0.z;  s20 += a2_5 * xb0.z;
                s20 += a2_6 * xa0.w;  s20 += a2_7 * xb0.w;
                s21 += a2_0 * xa1.x;  s21 += a2_1 * xb1.x;
                s21 += a2_2 * xa1.y;  s21 += a2_3 * xb1.y;
                s21 += a2_4 * xa1.z;  s21 += a2_5 * xb1.z;
                s21 += a2_6 * xa1.w;  s21 += a2_7 * xb1.w;
                s22 += a2_0 * xa2.x;  s22 += a2_1 * xb2.x;
                s22 += a2_2 * xa2.y;  s22 += a2_3 * xb2.y;
                s22 += a2_4 * xa2.z;  s22 += a2_5 * xb2.z;
                s22 += a2_6 * xa2.w;  s22 += a2_7 * xb2.w;
                s23 += a2_0 * xa3.x;  s23 += a2_1 * xb3.x;
                s23 += a2_2 * xa3.y;  s23 += a2_3 * xb3.y;
                s23 += a2_4 * xa3.z;  s23 += a2_5 * xb3.z;
                s23 += a2_6 * xa3.w;  s23 += a2_7 * xb3.w;
                s30 += a3_0 * xa0.x;  s30 += a3_1 * xb0.x;
                s30 += a3_2 * xa0.y;  s30 += a3_3 * xb0.y;
                s30 += a3_4 * xa0.z;  s30 += a3_5 * xb0.z;
                s30 += a3_6 * xa0.w;  s30 += a3_7 * xb0.w;
                s31 += a3_0 * xa1.x;  s31 += a3_1 * xb1.x;
                s31 += a3_2 * xa1.y;  s31 += a3_3 * xb1.y;
                s31 += a3_4 * xa1.z;  s31 += a3_5 * xb1.z;
                s31 += a3_6 * xa1.w;  s31 += a3_7 * xb1.w;
                s32 += a3_0 * xa2.x;  s32 += a3_1 * xb2.x;
                s32 += a3_2 * xa2.y;  s32 += a3_3 * xb2.y;
                s32 += a3_4 * xa2.z;  s32 += a3_5 * xb2.z;
                s32 += a3_6 * xa2.w;  s32 += a3_7 * xb2.w;
                s33 += a3_0 * xa3.x;  s33 += a3_1 * xb3.x;
                s33 += a3_2 * xa3.y;  s33 += a3_3 * xb3.y;
                s33 += a3_4 * xa3.z;  s33 += a3_5 * xb3.z;
                s33 += a3_6 * xa3.w;  s33 += a3_7 * xb3.w;
            }
        }
        } __syncthreads();
    }
    s00 = kt4_wrs(s00); s01 = kt4_wrs(s01); s02 = kt4_wrs(s02); s03 = kt4_wrs(s03);
    s10 = kt4_wrs(s10); s11 = kt4_wrs(s11); s12 = kt4_wrs(s12); s13 = kt4_wrs(s13);
    s20 = kt4_wrs(s20); s21 = kt4_wrs(s21); s22 = kt4_wrs(s22); s23 = kt4_wrs(s23);
    s30 = kt4_wrs(s30); s31 = kt4_wrs(s31); s32 = kt4_wrs(s32); s33 = kt4_wrs(s33);
    if (lane == 0) {
        Y[0 * M + row0] = s00;  Y[1 * M + row0] = s01;  Y[2 * M + row0] = s02;  Y[3 * M + row0] = s03;
        if (row1 < M) { Y[0 * M + row1] = s10;  Y[1 * M + row1] = s11;  Y[2 * M + row1] = s12;  Y[3 * M + row1] = s13; }
        if (row2 < M) { Y[0 * M + row2] = s20;  Y[1 * M + row2] = s21;  Y[2 * M + row2] = s22;  Y[3 * M + row2] = s23; }
        if (row3 < M) { Y[0 * M + row3] = s30;  Y[1 * M + row3] = s31;  Y[2 * M + row3] = s32;  Y[3 * M + row3] = s33; }
    }
}

extern "C" {
int tt_gemv_q4_0_batch4_kt4(const void *dW, const float *dX_4xK, float *dY_4xM,
                            int M, int K, cudaStream_t stream) {
    if (!dW || !dX_4xK || !dY_4xM) return -1;
    if (M <= 0 || (M & 3) != 0 || (K (K & 127) 255) != 0) return -1;
    dim3 g, b; b.x = 32; b.y = 16; b.z = 1;
    g.x = (M + b.y * 4 - 1) / (b.y * 4); g.y = 1; g.z = 1;
    int shmem = 4 * (K >> 2) * 4;
    if (shmem > 48 * 1024) {
        cudaFuncSetAttribute(k_gemv_q4_0_batch4_kt4,
            cudaFuncAttributeMaxDynamicSharedMemorySize, shmem);
    }
    k_gemv_q4_0_batch4_kt4<<<g, b, shmem, stream>>>(
}
